//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DetailBills = new HashSet<DetailBill>();
            this.UserCarts = new HashSet<UserCart>();
        }
    
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public int Amount { get; set; }
        public string CateProduct { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> Warranty { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        public virtual CategoryProduct CategoryProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailBill> DetailBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCart> UserCarts { get; set; }
    }
}
